name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Test FTP Connection
        run: |
            sudo apt-get update && sudo apt-get install -y lftp
            lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ${{ secrets.FTP_HOST }} -e "ls; bye"

    #   - name: Deploy to FTP
    #     uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #     with:
    #       server: ${{ secrets.FTP_HOST }}
    #       username: ${{ secrets.FTP_USERNAME }}
    #       password: ${{ secrets.FTP_PASSWORD }}
    #       protocol: ftp
    #       local-dir: ./dist/
    #       server-dir: /it.eds.co.th/
